## Tax Primer

In [7]:
import pandas as pd
import numpy as np
!pip install numpy_financial
import numpy_financial as npf
import plotly.graph_objects as go
import plotly.express as px
pd.options.display.float_format = '{:,.2f}'.format

Requirement already satisfied: numpy_financial in c:\users\kpc2\appdata\local\miniforge3\envs\sklearn-env\lib\site-packages (1.0.0)
Requirement already satisfied: numpy>=1.15 in c:\users\kpc2\appdata\local\miniforge3\envs\sklearn-env\lib\site-packages (from numpy_financial) (2.1.3)

In [8]:
LIMITS = [0, 11925, 48475, 103350, 197300, 250525, 626350]
RATES  = [0.1, 0.12, 0.22, 0.24, 0.32, 0.35, 0.37]

cols = ['lower','upper','rate','bin_income','bin_tax']
df = pd.DataFrame(dtype=float, columns=cols, index=1+np.arange(len(LIMITS)))
df['lower'] = LIMITS
df['upper'] = LIMITS[1:] + [np.inf]
df['rate']  = RATES
df

    lower      upper  rate  bin_income  bin_tax
1       0  11,925.00  0.10         NaN      NaN
2   11925  48,475.00  0.12         NaN      NaN
3   48475 103,350.00  0.22         NaN      NaN
4  103350 197,300.00  0.24         NaN      NaN
5  197300 250,525.00  0.32         NaN      NaN
6  250525 626,350.00  0.35         NaN      NaN
7  626350        inf  0.37         NaN      NaN

In [9]:
INCOME = 100000
df['bin_income']= np.where(INCOME>df.lower, 
                    np.where(INCOME>df.upper, df.upper-df.lower, INCOME-df.lower),
                    0)
df

    lower      upper  rate  bin_income  bin_tax
1       0  11,925.00  0.10   11,925.00      NaN
2   11925  48,475.00  0.12   36,550.00      NaN
3   48475 103,350.00  0.22   51,525.00      NaN
4  103350 197,300.00  0.24        0.00      NaN
5  197300 250,525.00  0.32        0.00      NaN
6  250525 626,350.00  0.35        0.00      NaN
7  626350        inf  0.37        0.00      NaN

In [10]:
# Check that sum of df.bin_income equals taxable income
df.bin_income.sum()

100000.0

In [11]:
df['bin_tax'] = df.bin_income*df.rate
df

    lower      upper  rate  bin_income   bin_tax
1       0  11,925.00  0.10   11,925.00  1,192.50
2   11925  48,475.00  0.12   36,550.00  4,386.00
3   48475 103,350.00  0.22   51,525.00 11,335.50
4  103350 197,300.00  0.24        0.00      0.00
5  197300 250,525.00  0.32        0.00      0.00
6  250525 626,350.00  0.35        0.00      0.00
7  626350        inf  0.37        0.00      0.00

In [12]:
# Total tax
total_tax = df.bin_tax.sum()
print(f'Total tax: ${total_tax:,.2f}')

Total tax: $16,914.00

In [13]:
def tax_single_filer(income):
    LIMITS = [0, 11925, 48475, 103350, 197300, 250525, 626350]
    RATES  = [0.1, 0.12, 0.22, 0.24, 0.32, 0.35, 0.37]
    cols = ['lower','upper','rate','bin_income','bin_tax']
    df = pd.DataFrame(dtype=float, columns=cols, index=1+np.arange(len(LIMITS)))
    df['lower'] = LIMITS
    df['upper'] = LIMITS[1:] + [np.inf]
    df['rate']  = RATES
    df['bin_income']= np.where(income>df.lower, 
                    np.where(income>df.upper, df.upper-df.lower, income-df.lower),
                    0)
    df['bin_tax'] = df.bin_income*df.rate
    return df.bin_tax.sum()

In [14]:
incomes = np.arange(1000,1001000,1000)
taxes = [tax_single_filer(x) for x in incomes]

In [15]:
# Scatter plot of tax due
fig = go.Figure()
trace  = go.Scatter(x=incomes, y=taxes, mode="lines")
fig.add_trace(trace)

# Formatting
fig.update_xaxes(title='Income (after deductions)',tickformat=",.2f")
fig.update_yaxes(title='Tax',tickformat=",.2f")
fig.show()

In [16]:
# Scatter plot of average tax rate
fig = go.Figure()
trace  = go.Scatter(x=incomes, y=taxes/incomes, mode="lines")
fig.add_trace(trace)

# Formatting
fig.update_xaxes(title='Income (after deductions)',tickformat=",.0f")
fig.update_yaxes(title='Average Tax Rate',tickformat=",.2%")
fig.show()

### Example

- Consider a single investor earning \$80,000 per year.  
- Assume they take the standard deduction of \$15,750.
- Under the 2025 tax rates & brackets, what is the investor's tax bill if do not have any other deductions?

In [26]:
GROSS_INCOME = 80000
DEDUCTIBLE_SAVINGS = 0
STANDARD_DEDUCTION = 15750
tax1 = tax_single_filer(GROSS_INCOME - DEDUCTIBLE_SAVINGS - STANDARD_DEDUCTION)
tax1

9049.0

- Under the 2025 tax rates & brackets, what is the investor's tax bill if they have contributed \$7,000 to a traditional IRA?

In [27]:
GROSS_INCOME = 80000
DEDUCTIBLE_SAVINGS = 7000
STANDARD_DEDUCTION = 15750
tax2 = tax_single_filer(GROSS_INCOME - DEDUCTIBLE_SAVINGS - STANDARD_DEDUCTION)
tax2

7509.0

In [31]:
df[['lower','upper','rate']]

    lower      upper  rate
1       0  11,925.00  0.10
2   11925  48,475.00  0.12
3   48475 103,350.00  0.22
4  103350 197,300.00  0.24
5  197300 250,525.00  0.32
6  250525 626,350.00  0.35
7  626350        inf  0.37

In [32]:
pre_savings_taxable_income = GROSS_INCOME - STANDARD_DEDUCTION
marginal_rate = df[(df.lower < pre_savings_taxable_income) & (df.upper > pre_savings_taxable_income)].rate.values[0]
print(f"Pre-Savings Taxable Income:\t${pre_savings_taxable_income:,.0f}")
print(f"Marginal Rate:\t\t\t{marginal_rate:.0%}")

Pre-Savings Taxable Income:	$64,250
Marginal Rate:			22%

In [33]:
print(marginal_rate*DEDUCTIBLE_SAVINGS)
print(tax1-tax2)

1540.0
1540.0